add guide for 'upgrade by installing again' to close 18
qiime2/docs.qiime2.org pull request #20
Opened 2018-08-25 18:35 UTC by colinbrislawn

2018-08-28 19:08 UTC, ebolyen commented on 2018.6/_sources/install/native.txt
> +How do I update to the newest version of Qiime?
`Qiime` -> `QIIME 2`

2018-08-28 19:09 UTC, ebolyen requested changes
Thanks @colinbrislawn! Just a term swap, otherwise LGTM.

2018-08-28 19:09 UTC, ebolyen commented on 2018.6/_sources/install/native.txt
> +In order to to update/upgrade to the newest release, you just install the newest version in a new conda environment by following the instructions above. Then you will have two conda environments, one
`Qiime` -> `QIIME 2`

2018-08-28 22:31 UTC, ebolyen commented
Sorry to be nitpicky, but can QIIME be spelled in all caps? Thanks!

2018-08-29 15:34 UTC, colinbrislawn commented
Updated! (Good catch. Clearly I didn't read the style guide...)

2018-08-29 15:34 UTC, thermokarst commented
Oops, this PR is on the built docs, not the docs source! We should be making these changes at https://github.com/qiime2/docs - @colinbrislawn would you mind re-opening there? The same edits should go into https://github.com/qiime2/docs/blob/master/source/install/native.rst

Thanks!

2018-08-29 15:35 UTC, thermokarst commented
Sorry, didn't mean to close, hit the wrong button. I would like to close, but only after you confirm @colinbrislawn!

2018-08-29 15:48 UTC, colinbrislawn commented
Yes, I'll open a new PR on the source.

... Does this repo just old the rendered documents, while all the source is somewhere else? Can we put a note of that somewhere?

2018-08-29 15:48 UTC, closed without merging

2018-08-29 15:54 UTC, thermokarst commented
Thanks @colinbrislawn!

> ... Does this repo just holds the rendered documents, while all the source is somewhere else? Can we put a note of that somewhere?

![screen shot 2018-08-29 at 8 53 45 am](https://user-images.githubusercontent.com/274668/44799565-19f1e880-ab69-11e8-9c6a-45fb5983e9aa.png)

2018-08-29 16:03 UTC, colinbrislawn commented
Oh that's exactly the warning I was suggesting.

I can't believe I missed that... 🤕

2018-08-29 16:06 UTC, ebolyen commented
oh gosh... I completely missed this as well >_<